site_name: "Deep Learning Workshop 2026"
site_description: "The tutorial about deep learning for beginners"
site_author: "sstia-trilobit"
site_url: "https://trilobit-coder.github.io/deeplearning/"
repo_url: "https://github.com/trilobit-coder/deeplearning/"
repo_name: deeplearning

theme:
  name: material
  language: en
  logo: assets/logo.png      
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)" 

    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - mkdocs-video:
      is_video: True

nav:
  - Home: index.md
  - Part1:
      - "KNN and Linear Classifier": Part1/Linear_Classifier.md
      - "CNN": Part1/CNN.md